name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby:
        - "3.3"
        - "3.2"
        - "3.1"
        - "3.0"
        - debug
        include:
        - { os: windows-latest, ruby: mswin }
        - { os: ubuntu-latest , ruby: jruby-head }
        exclude:
        # "debug" is invalid on windows-latest.
        - { os: windows-latest, ruby: debug }


    steps:
    - uses: actions/checkout@v1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rake test

    - run: bundle exec rake build

    - run: gem install pkg/*.gem
