name: CI

on:
- push
- pull_request

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby_version:
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - jruby
        - truffleruby

    steps:
    - uses: actions/checkout@v1

    - name: Setup Ruby
      uses: eregon/use-ruby-action@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
